services:

  api:
    container_name: Travelmate-api
    build: .
    command: npm start
    ports:
      - "5000:5000"
    # environment:
    #   - MONGO_URI=<Your_MongoDB_Atlas_URI>
    env_file: .env
    restart: unless-stopped
    # depends_on: []
    volumes:
      # - .:/usr/src/app
      - /usr/src/app/node_modules